### ISSUE TITLE
EMV WebServices

### ISSUE THREAD

**Issue by CoderBlaine** [AuthorizeNet/inperson-sdk-windows#2]
Hi,

I was just reviewing your EMV options and it appears that the only way to integrate EMV payments through Authorize.net is to use these SDK's.  From a partner perspective this seems a little bit like a nightmare.

In our particular case it would be much easier to have an authorize.net cloud middleware that we could simply send a command to then have it work all the magic on the EMV terminal sort of like (docs.paymentengine.io)

If I understand these Docs correctly, and your partner wants to use a webservice to make the EMV reader work they have to:

1) Have a web server to accept incoming requests
2) Translate these requests then send the request to your SDK functions
3) This software would have to be run on each Authorize.net mutual client's network, and the partner would be the ones to support any issues with it.

Given this, are their plans for a cloud middleware anytime soon?

**Comment by ywang7** [comment]
Hi CoderBlaine,

Thanks for the comments, the Windows in-person SDK is designed to work with our supported card readers only(https://partner.posportal.com/authorizenet/auth/), we won't be allowing the raw EMV data to be processed since the data format has to be certified end-to-end with our processors. If you are just looking for web service just to charge the credit card, you may refer to the Authorize.Net Accept solution, which can be found here:
https://github.com/AuthorizeNet/accept-sample-app

Please let me know if there is any further questions.

Thanks,
Alex
